name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic test
      run: |
        python -c "print('✅ Basic test passed!')"
        python -c "import torch; print(f'✅ PyTorch version: {torch.__version__}')"
        python -c "import cv2; print(f'✅ OpenCV version: {cv2.__version__}')"
        python -c "import mediapipe; print(f'✅ MediaPipe version: {mediapipe.__version__}')" 